name: online_voting_system
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Adjusted Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.2
  
  
  flutter_svg: ^2.0.9
  flutter_ui_toolkit: ^0.0.3+9
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  local_auth: ^2.1.8
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  get_it: ^7.6.7
  glassmorphism: ^3.0.0
  glassmorphism_ui: ^0.3.0
  web3dart: ^2.7.2
  cloud_firestore: ^4.15.5
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.5.0
  intl_phone_number_input: ^0.7.4
  country_code_picker: ^3.0.0
  libphonenumber_plugin: ^0.3.3
  flutter_libphonenumber: ^2.2.1
  go_router: 13.2.1
  sliding_clipped_nav_bar: 3.1.1
  confetti: ^0.7.0
 












dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



flutter:
  uses-material-design: true
  assets:
    - web/
    - assets/indian.jpg
    - assets/svgs/emblem.svg
    - assets/icons/chat.svg
    - assets/abi.json
    - assets/images/
    - assets/icons/chat.jpg
    - assets/icons/uu.jpg
    - assets/icons/Ashok.jpg
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 100
